services:
  - type: web
    name: chandrasekar-store
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn groceryshop.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: groceryshop.settings
      - key: PYTHON_VERSION
        value: 3.12.4
